#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Zcy@0808
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
